# Generated by Django 4.2.7 on 2025-11-20 09:29

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên khu vực")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Ranh giới"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Khu vực",
                "verbose_name_plural": "Khu vực",
                "db_table": "areas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tên lớp")),
                (
                    "grade_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Khối",
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phòng học"
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Giáo viên chủ nhiệm",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="Năm học"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Lớp học",
                "verbose_name_plural": "Lớp học",
                "db_table": "classes",
                "ordering": ["grade_level", "name"],
                "unique_together": {("name", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Mã học sinh",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Ngày sinh")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                ("address", models.TextField(verbose_name="Địa chỉ")),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Vị trí đón"
                    ),
                ),
                (
                    "dropoff_location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Vị trí trả"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="students/", verbose_name="Ảnh"
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nhu cầu đặc biệt"
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tình trạng sức khỏe"
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Nhóm máu"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="students.area",
                        verbose_name="Khu vực",
                    ),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="students.class",
                        verbose_name="Lớp học",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="authentication.parent",
                        verbose_name="Phụ huynh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Học sinh",
                "verbose_name_plural": "Học sinh",
                "db_table": "students",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        help_text="Loại ghi chú (sức khỏe, hành vi, chung)",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Tiêu đề ghi chú"),
                ),
                ("content", models.TextField(verbose_name="Nội dung ghi chú")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Quan trọng?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ghi chú học sinh",
                "verbose_name_plural": "Ghi chú học sinh",
                "db_table": "student_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="Loại tài liệu (giấy khai sinh, hồ sơ sức khỏe, …)",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Tên tài liệu"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="student_documents/", verbose_name="Tập tin"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ngày tải lên"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="students.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tải lên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tài liệu học sinh",
                "verbose_name_plural": "Tài liệu học sinh",
                "db_table": "student_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Họ tên")),
                (
                    "relationship",
                    models.CharField(max_length=100, verbose_name="Quan hệ"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Số điện thoại"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Liên hệ chính"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="students.student",
                        verbose_name="Học sinh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liên hệ khẩn cấp",
                "verbose_name_plural": "Liên hệ khẩn cấp",
                "db_table": "emergency_contacts",
                "ordering": ["-is_primary", "name"],
            },
        ),
    ]
