# Generated by Django 4.2.7 on 2025-11-19 14:16

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_driver_options_alter_parent_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["name"],
                "verbose_name": "Khu vực",
                "verbose_name_plural": "Khu vực",
            },
        ),
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["grade_level", "name"],
                "verbose_name": "Lớp học",
                "verbose_name_plural": "Lớp học",
            },
        ),
        migrations.AlterModelOptions(
            name="emergencycontact",
            options={
                "ordering": ["-is_primary", "name"],
                "verbose_name": "Liên hệ khẩn cấp",
                "verbose_name_plural": "Liên hệ khẩn cấp",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Học sinh",
                "verbose_name_plural": "Học sinh",
            },
        ),
        migrations.AlterModelOptions(
            name="studentdocument",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Tài liệu học sinh",
                "verbose_name_plural": "Tài liệu học sinh",
            },
        ),
        migrations.AlterModelOptions(
            name="studentnote",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ghi chú học sinh",
                "verbose_name_plural": "Ghi chú học sinh",
            },
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_student_cdda5e_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_full_na_365b2b_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_is_acti_4aecc9_idx",
        ),
        migrations.AlterField(
            model_name="area",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326, verbose_name="Ranh giới"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="area",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên khu vực"),
        ),
        migrations.AlterField(
            model_name="area",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="class",
            name="academic_year",
            field=models.CharField(max_length=20, verbose_name="Năm học"),
        ),
        migrations.AlterField(
            model_name="class",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="class",
            name="grade_level",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Khối",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tên lớp"),
        ),
        migrations.AlterField(
            model_name="class",
            name="room_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phòng học"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="teacher_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Giáo viên chủ nhiệm",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Liên hệ chính"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Họ tên"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Số điện thoại"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="relationship",
            field=models.CharField(max_length=100, verbose_name="Quan hệ"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contacts",
                to="students.student",
                verbose_name="Học sinh",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="student",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.area",
                verbose_name="Khu vực",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="blood_type",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="Nhóm máu"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="students.class",
                verbose_name="Lớp học",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(verbose_name="Ngày sinh"),
        ),
        migrations.AlterField(
            model_name="student",
            name="dropoff_location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Vị trí trả"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Họ và tên"),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                max_length=10,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="student",
            name="medical_conditions",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tình trạng sức khỏe"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="authentication.parent",
                verbose_name="Phụ huynh",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="students/", verbose_name="Ảnh"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="pickup_location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Vị trí đón"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="special_needs",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nhu cầu đặc biệt"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_code",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Mã học sinh"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="document_type",
            field=models.CharField(
                help_text="Loại tài liệu (giấy khai sinh, hồ sơ sức khỏe, …)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="file",
            field=models.FileField(
                upload_to="student_documents/", verbose_name="Tập tin"
            ),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Tên tài liệu"),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tải lên"),
        ),
        migrations.AlterField(
            model_name="studentdocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tải lên",
            ),
        ),
        migrations.AlterField(
            model_name="studentnote",
            name="content",
            field=models.TextField(verbose_name="Nội dung ghi chú"),
        ),
        migrations.AlterField(
            model_name="studentnote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="studentnote",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="Quan trọng?"),
        ),
        migrations.AlterField(
            model_name="studentnote",
            name="note_type",
            field=models.CharField(
                help_text="Loại ghi chú (sức khỏe, hành vi, chung)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="studentnote",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Tiêu đề ghi chú"),
        ),
        migrations.AlterField(
            model_name="studentnote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
    ]
