# Generated by Django 4.2.7 on 2025-11-20 15:31

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã tuyến"
                    ),
                ),
                (
                    "route_name",
                    models.CharField(max_length=255, verbose_name="Tên tuyến"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả"),
                ),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Đón học sinh"),
                            ("dropoff", "Trả học sinh"),
                            ("both", "Đón và trả"),
                        ],
                        max_length=20,
                        verbose_name="Loại tuyến",
                    ),
                ),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326, verbose_name="Đường đi"
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Thời gian dự kiến (phút)"
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tổng quãng đường (km)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="students.area",
                        verbose_name="Khu vực",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="authentication.driver",
                        verbose_name="Tài xế",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tuyến đường",
                "verbose_name_plural": "Tuyến đường",
                "db_table": "routes",
                "ordering": ["route_code"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_order", models.IntegerField(verbose_name="Thứ tự điểm dừng")),
                (
                    "stop_name",
                    models.CharField(max_length=255, verbose_name="Tên điểm dừng"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Vị trí"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "estimated_arrival",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Giờ đến dự kiến"
                    ),
                ),
                (
                    "estimated_departure",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Giờ đi dự kiến"
                    ),
                ),
                (
                    "stop_duration",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Thời gian dừng (phút)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                        verbose_name="Tuyến đường",
                    ),
                ),
            ],
            options={
                "verbose_name": "Điểm dừng",
                "verbose_name_plural": "Điểm dừng",
                "db_table": "route_stops",
                "ordering": ["route", "stop_order"],
                "unique_together": {("route", "stop_order")},
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Biển số xe"
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(max_length=50, verbose_name="Loại xe"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(5)],
                        verbose_name="Sức chứa",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Mẫu xe"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Năm sản xuất"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Màu sắc"
                    ),
                ),
                (
                    "insurance_expiry",
                    models.DateField(verbose_name="Ngày hết hạn bảo hiểm"),
                ),
                (
                    "registration_expiry",
                    models.DateField(verbose_name="Ngày hết hạn đăng kiểm"),
                ),
                (
                    "last_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bảo dưỡng lần cuối"
                    ),
                ),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bảo dưỡng lần sau"
                    ),
                ),
                (
                    "gps_device_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mã thiết bị GPS",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang hoạt động"),
                            ("maintenance", "Đang bảo trì"),
                            ("inactive", "Ngừng hoạt động"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Phương tiện",
                "verbose_name_plural": "Phương tiện",
                "db_table": "vehicles",
                "ordering": ["plate_number"],
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(max_length=100, verbose_name="Loại bảo trì"),
                ),
                ("description", models.TextField(verbose_name="Mô tả chi tiết")),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Chi phí (VNĐ)",
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Thực hiện bởi",
                    ),
                ),
                ("performed_at", models.DateTimeField(verbose_name="Ngày bảo trì")),
                (
                    "next_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Lịch bảo trì tiếp theo"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú thêm"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="routes.vehicle",
                        verbose_name="Xe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảo trì phương tiện",
                "verbose_name_plural": "Bảo trì phương tiện",
                "db_table": "vehicle_maintenance",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="routes.vehicle",
                verbose_name="Xe",
            ),
        ),
        migrations.CreateModel(
            name="StudentRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Đón"),
                            ("dropoff", "Trả"),
                            ("both", "Cả hai"),
                        ],
                        help_text="Đón / Trả / Cả hai",
                        max_length=20,
                        verbose_name="Loại phân công",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Ngày bắt đầu")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày kết thúc"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="routes.route",
                        verbose_name="Tuyến xe",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="routes.routestop",
                        verbose_name="Điểm đón/trả",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_assignments",
                        to="students.student",
                        verbose_name="Học sinh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phân công tuyến cho học sinh",
                "verbose_name_plural": "Phân công tuyến cho học sinh",
                "db_table": "student_routes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "is_active"],
                        name="student_rou_student_81ac85_idx",
                    ),
                    models.Index(
                        fields=["route", "is_active"],
                        name="student_rou_route_i_c926e2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        help_text="0=Thứ 2, 6=Chủ nhật",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MinValueValidator(6),
                        ],
                        verbose_name="Thứ trong tuần",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Giờ bắt đầu")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Giờ kết thúc"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="routes.route",
                        verbose_name="Tuyến xe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch chạy tuyến",
                "verbose_name_plural": "Lịch chạy tuyến",
                "db_table": "route_schedules",
                "ordering": ["route", "day_of_week", "start_time"],
                "unique_together": {("route", "day_of_week", "start_time")},
            },
        ),
    ]
