# Generated by Django 4.2.7 on 2025-11-17 06:16

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_code", models.CharField(max_length=50, unique=True)),
                ("route_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pick Up"),
                            ("dropoff", "Drop Off"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                (
                    "total_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance in kilometers",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="students.area",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="authentication.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "routes",
                "ordering": ["route_code"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_order", models.IntegerField()),
                ("stop_name", models.CharField(max_length=255)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("address", models.TextField(blank=True, null=True)),
                ("estimated_arrival", models.TimeField(blank=True, null=True)),
                ("estimated_departure", models.TimeField(blank=True, null=True)),
                (
                    "stop_duration",
                    models.IntegerField(
                        default=2,
                        help_text="Duration in minutes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Stop",
                "verbose_name_plural": "Route Stops",
                "db_table": "route_stops",
                "ordering": ["route", "stop_order"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                ("vehicle_type", models.CharField(max_length=50)),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(5)]
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("insurance_expiry", models.DateField()),
                ("registration_expiry", models.DateField()),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                (
                    "gps_device_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Under Maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "db_table": "vehicles",
                "ordering": ["plate_number"],
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("performed_at", models.DateTimeField()),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="routes.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_maintenance",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        help_text="0=Monday, 6=Sunday",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MinValueValidator(6),
                        ],
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Schedule",
                "verbose_name_plural": "Route Schedules",
                "db_table": "route_schedules",
                "ordering": ["route", "day_of_week", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="routes.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="StudentRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pick Up"),
                            ("dropoff", "Drop Off"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="routes.route",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="routes.routestop",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_assignments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Route Assignment",
                "verbose_name_plural": "Student Route Assignments",
                "db_table": "student_routes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "is_active"],
                        name="student_rou_student_81ac85_idx",
                    ),
                    models.Index(
                        fields=["route", "is_active"],
                        name="student_rou_route_i_c926e2_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="routestop",
            index=models.Index(
                fields=["route", "stop_order"], name="route_stops_route_i_9121b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routestop",
            unique_together={("route", "stop_order")},
        ),
        migrations.AlterUniqueTogether(
            name="routeschedule",
            unique_together={("route", "day_of_week", "start_time")},
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["route_code"], name="routes_route_c_b515e8_idx"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["is_active"], name="routes_is_acti_9ece4b_idx"),
        ),
    ]
