# Generated by Django 4.2.7 on 2025-11-19 14:16

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_area_options_alter_class_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0003_alter_driver_options_alter_parent_options_and_more"),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={
                "ordering": ["route_code"],
                "verbose_name": "Tuyến đường",
                "verbose_name_plural": "Tuyến đường",
            },
        ),
        migrations.AlterModelOptions(
            name="routeschedule",
            options={
                "ordering": ["route", "day_of_week", "start_time"],
                "verbose_name": "Lịch chạy tuyến",
                "verbose_name_plural": "Lịch chạy tuyến",
            },
        ),
        migrations.AlterModelOptions(
            name="routestop",
            options={
                "ordering": ["route", "stop_order"],
                "verbose_name": "Điểm dừng",
                "verbose_name_plural": "Điểm dừng",
            },
        ),
        migrations.AlterModelOptions(
            name="studentroute",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Phân công tuyến cho học sinh",
                "verbose_name_plural": "Phân công tuyến cho học sinh",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicle",
            options={
                "ordering": ["plate_number"],
                "verbose_name": "Phương tiện",
                "verbose_name_plural": "Phương tiện",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclemaintenance",
            options={
                "ordering": ["-performed_at"],
                "verbose_name": "Bảo trì phương tiện",
                "verbose_name_plural": "Bảo trì phương tiện",
            },
        ),
        migrations.RemoveIndex(
            model_name="route",
            name="routes_route_c_b515e8_idx",
        ),
        migrations.RemoveIndex(
            model_name="route",
            name="routes_is_acti_9ece4b_idx",
        ),
        migrations.RemoveIndex(
            model_name="routestop",
            name="route_stops_route_i_9121b1_idx",
        ),
        migrations.AlterField(
            model_name="route",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="students.area",
                verbose_name="Khu vực",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="route",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="route",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="authentication.driver",
                verbose_name="Tài xế",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="estimated_duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Thời gian dự kiến (phút)"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="route",
            name="path",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, null=True, srid=4326, verbose_name="Đường đi"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Mã tuyến"),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_name",
            field=models.CharField(max_length=255, verbose_name="Tên tuyến"),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_type",
            field=models.CharField(
                choices=[
                    ("pickup", "Đón học sinh"),
                    ("dropoff", "Trả học sinh"),
                    ("both", "Đón và trả"),
                ],
                max_length=20,
                verbose_name="Loại tuyến",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="total_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Tổng quãng đường (km)",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="routes.vehicle",
                verbose_name="Xe",
            ),
        ),
        migrations.AlterField(
            model_name="routeschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="routeschedule",
            name="day_of_week",
            field=models.IntegerField(
                help_text="0=Thứ 2, 6=Chủ nhật",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MinValueValidator(6),
                ],
                verbose_name="Thứ trong tuần",
            ),
        ),
        migrations.AlterField(
            model_name="routeschedule",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Giờ kết thúc"),
        ),
        migrations.AlterField(
            model_name="routeschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động?"),
        ),
        migrations.AlterField(
            model_name="routeschedule",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="routes.route",
                verbose_name="Tuyến xe",
            ),
        ),
        migrations.AlterField(
            model_name="routeschedule",
            name="start_time",
            field=models.TimeField(verbose_name="Giờ bắt đầu"),
        ),
        migrations.AlterField(
            model_name="routeschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="estimated_arrival",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Giờ đến dự kiến"
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="estimated_departure",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Giờ đi dự kiến"
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Vị trí"
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="routes.route",
                verbose_name="Tuyến đường",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="stop_duration",
            field=models.IntegerField(
                default=2,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Thời gian dừng (phút)",
            ),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="stop_name",
            field=models.CharField(max_length=255, verbose_name="Tên điểm dừng"),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="stop_order",
            field=models.IntegerField(verbose_name="Thứ tự điểm dừng"),
        ),
        migrations.AlterField(
            model_name="routestop",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="assignment_type",
            field=models.CharField(
                choices=[("pickup", "Đón"), ("dropoff", "Trả"), ("both", "Cả hai")],
                help_text="Đón / Trả / Cả hai",
                max_length=20,
                verbose_name="Loại phân công",
            ),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày kết thúc"),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động?"),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assignments",
                to="routes.route",
                verbose_name="Tuyến xe",
            ),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="start_date",
            field=models.DateField(verbose_name="Ngày bắt đầu"),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_assignments",
                to="routes.routestop",
                verbose_name="Điểm đón/trả",
            ),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_assignments",
                to="students.student",
                verbose_name="Học sinh",
            ),
        ),
        migrations.AlterField(
            model_name="studentroute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="capacity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(5)],
                verbose_name="Sức chứa",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Màu sắc"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="gps_device_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Mã thiết bị GPS"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="insurance_expiry",
            field=models.DateField(verbose_name="Ngày hết hạn bảo hiểm"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="last_maintenance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Bảo dưỡng lần cuối"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Mẫu xe"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="next_maintenance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Bảo dưỡng lần sau"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plate_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Biển số xe"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="registration_expiry",
            field=models.DateField(verbose_name="Ngày hết hạn đăng kiểm"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Đang hoạt động"),
                    ("maintenance", "Đang bảo trì"),
                    ("inactive", "Ngừng hoạt động"),
                ],
                default="active",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(max_length=50, verbose_name="Loại xe"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Năm sản xuất"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Chi phí (VNĐ)",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="description",
            field=models.TextField(verbose_name="Mô tả chi tiết"),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="maintenance_type",
            field=models.CharField(max_length=100, verbose_name="Loại bảo trì"),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="next_maintenance_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Lịch bảo trì tiếp theo"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú thêm"),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="performed_at",
            field=models.DateTimeField(verbose_name="Ngày bảo trì"),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="performed_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Thực hiện bởi"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_records",
                to="routes.vehicle",
                verbose_name="Xe",
            ),
        ),
    ]
