# Generated by Django 4.2.7 on 2025-11-20 09:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("routes", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_date", models.DateField()),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("morning_pickup", "Morning Pick Up"),
                            ("afternoon_dropoff", "Afternoon Drop Off"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_start_time", models.DateTimeField()),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("checked_in_students", models.IntegerField(default=0)),
                ("checked_out_students", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="authentication.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="routes.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="routes.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "trips",
                "ordering": ["-trip_date", "-scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="LocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "db_table": "location_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StopArrival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_arrival", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("students_boarded", models.IntegerField(default=0)),
                ("students_alighted", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routes.routestop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_arrivals",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "db_table": "stop_arrivals",
                "ordering": ["scheduled_arrival"],
                "unique_together": {("trip", "stop")},
            },
        ),
    ]
