# Generated by Django 4.2.7 on 2025-11-17 06:16

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("routes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_date", models.DateField()),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("morning_pickup", "Morning Pick Up"),
                            ("afternoon_dropoff", "Afternoon Drop Off"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_start_time", models.DateTimeField()),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("delayed", "Delayed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("checked_in_students", models.IntegerField(default=0)),
                ("checked_out_students", models.IntegerField(default=0)),
                ("absent_students", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="authentication.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="routes.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="routes.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "db_table": "trips",
                "ordering": ["-trip_date", "-scheduled_start_time"],
            },
        ),
        migrations.CreateModel(
            name="TripIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("vehicle_breakdown", "Vehicle Breakdown"),
                            ("traffic_jam", "Traffic Jam"),
                            ("weather", "Weather Issue"),
                            ("student_incident", "Student Incident"),
                            ("accident", "Accident"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="trip_issues/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trip_issues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StopArrival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_arrival", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("students_boarded", models.IntegerField(default=0)),
                ("students_alighted", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="routes.routestop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_arrivals",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "db_table": "stop_arrivals",
                "ordering": ["scheduled_arrival"],
            },
        ),
        migrations.CreateModel(
            name="LocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GPS accuracy in meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Speed in km/h",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Direction in degrees (0-360)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Altitude in meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("battery_level", models.IntegerField(blank=True, null=True)),
                ("is_online", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to="authentication.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Log",
                "verbose_name_plural": "Location Logs",
                "db_table": "location_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ETARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("estimated_arrival", models.DateTimeField()),
                ("actual_arrival", models.DateTimeField(blank=True, null=True)),
                (
                    "distance_remaining",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance in kilometers",
                        max_digits=10,
                    ),
                ),
                ("estimated_time_minutes", models.IntegerField()),
                (
                    "prediction_error_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eta_records",
                        to="routes.routestop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eta_records",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "db_table": "eta_records",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["trip_date", "status"], name="trips_trip_da_c0d77a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["driver", "status"], name="trips_driver__f38efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["route", "trip_date"], name="trips_route_i_4c4a9f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stoparrival",
            unique_together={("trip", "stop")},
        ),
        migrations.AddIndex(
            model_name="locationlog",
            index=models.Index(
                fields=["trip", "timestamp"], name="location_lo_trip_id_e7be45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationlog",
            index=models.Index(
                fields=["driver", "timestamp"], name="location_lo_driver__1b6b27_idx"
            ),
        ),
    ]
