# Generated by Django 4.2.7 on 2025-11-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
        ("authentication", "0002_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETARecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_arrival", models.DateTimeField()),
                (
                    "distance_remaining",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("estimated_time_minutes", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "eta_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="locationlog",
            name="accuracy",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="locationlog",
            name="heading",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="stoparrival",
            name="actual_departure",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stoparrival",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="absent_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trip",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="locationlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="driver",
            field=models.ForeignKey(
                help_text="Tài xế phụ trách",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="authentication.driver",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                help_text="Tuyến đường của chuyến đi",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="routes.route",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                help_text="Xe thực hiện chuyến",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="routes.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="locationlog",
            index=models.Index(
                fields=["trip", "-timestamp"], name="location_lo_trip_id_f47670_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="locationlog",
            index=models.Index(
                fields=["timestamp"], name="location_lo_timesta_91cbb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["trip_date", "status"], name="trips_trip_da_c0d77a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["route", "trip_date"], name="trips_route_i_4c4a9f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["scheduled", "in_progress"])),
                fields=("vehicle", "trip_date", "trip_type"),
                name="unique_vehicle_per_trip",
            ),
        ),
        migrations.AddConstraint(
            model_name="trip",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["scheduled", "in_progress"])),
                fields=("driver", "trip_date", "trip_type"),
                name="unique_driver_per_trip",
            ),
        ),
        migrations.AddField(
            model_name="etarecord",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="routes.routestop"
            ),
        ),
        migrations.AddField(
            model_name="etarecord",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eta_records",
                to="tracking.trip",
            ),
        ),
        migrations.AddIndex(
            model_name="etarecord",
            index=models.Index(
                fields=["trip", "stop", "-created_at"],
                name="eta_records_trip_id_64044e_idx",
            ),
        ),
    ]
