# Generated by Django 4.2.7 on 2025-11-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True, unique=True)),
                ("total_trips", models.IntegerField(default=0)),
                ("completed_trips", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("total_present", models.IntegerField(default=0)),
                ("total_absent", models.IntegerField(default=0)),
                ("on_time_trips", models.IntegerField(default=0)),
                ("delayed_trips", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="TripPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_duration", models.IntegerField(blank=True, null=True)),
                ("actual_duration", models.IntegerField(blank=True, null=True)),
                ("delay_minutes", models.IntegerField(default=0)),
                ("is_on_time", models.BooleanField(default=True)),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trip_performance",
                "ordering": ["-created_at"],
            },
        ),
    ]
