# Generated by Django 4.2.7 on 2025-11-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
        ("authentication", "0001_initial"),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True, unique=True)),
                ("total_trips", models.IntegerField(default=0)),
                ("completed_trips", models.IntegerField(default=0)),
                ("cancelled_trips", models.IntegerField(default=0)),
                ("in_progress_trips", models.IntegerField(default=0)),
                ("total_students_transported", models.IntegerField(default=0)),
                ("total_present", models.IntegerField(default=0)),
                ("total_absent", models.IntegerField(default=0)),
                ("total_late", models.IntegerField(default=0)),
                (
                    "on_time_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "late_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_delay_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_duration_minutes", models.IntegerField(default=0)),
                ("total_issues", models.IntegerField(default=0)),
                ("critical_issues", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="SystemStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_parents", models.IntegerField(default=0)),
                ("active_drivers", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("active_students", models.IntegerField(default=0)),
                ("total_vehicles", models.IntegerField(default=0)),
                ("active_vehicles", models.IntegerField(default=0)),
                ("total_routes", models.IntegerField(default=0)),
                ("active_routes", models.IntegerField(default=0)),
                (
                    "overall_on_time_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overall_attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TripPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_duration",
                    models.IntegerField(blank=True, help_text="Minutes", null=True),
                ),
                (
                    "actual_duration",
                    models.IntegerField(blank=True, help_text="Minutes", null=True),
                ),
                ("delay_minutes", models.IntegerField(default=0)),
                ("is_on_time", models.BooleanField(default=True)),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "average_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("stops_completed", models.IntegerField(default=0)),
                ("stops_total", models.IntegerField(default=0)),
                ("issues_reported", models.IntegerField(default=0)),
                (
                    "driver_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("parent_feedback_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="tracking.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trip_performance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoutePerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_trips", models.IntegerField(default=0)),
                ("completed_trips", models.IntegerField(default=0)),
                (
                    "average_duration",
                    models.IntegerField(default=0, help_text="Minutes"),
                ),
                (
                    "on_time_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_delay_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("average_students_per_trip", models.IntegerField(default=0)),
                (
                    "average_attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "db_table": "route_performance_reports",
                "ordering": ["-start_date"],
                "unique_together": {("route", "report_type", "start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="DriverPerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_trips", models.IntegerField(default=0)),
                ("completed_trips", models.IntegerField(default=0)),
                ("cancelled_trips", models.IntegerField(default=0)),
                ("on_time_trips", models.IntegerField(default=0)),
                ("delayed_trips", models.IntegerField(default=0)),
                (
                    "on_time_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_delay_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                ("total_issues", models.IntegerField(default=0)),
                ("critical_issues", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="authentication.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_performance_reports",
                "ordering": ["-start_date"],
                "unique_together": {
                    ("driver", "report_type", "start_date", "end_date")
                },
            },
        ),
    ]
