# Generated by Django 4.2.7 on 2025-11-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
        ("authentication", "0002_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_parents", models.IntegerField(default=0)),
                ("active_drivers", models.IntegerField(default=0)),
                ("total_students", models.IntegerField(default=0)),
                ("active_students", models.IntegerField(default=0)),
                ("total_vehicles", models.IntegerField(default=0)),
                ("active_vehicles", models.IntegerField(default=0)),
                ("total_routes", models.IntegerField(default=0)),
                ("active_routes", models.IntegerField(default=0)),
                (
                    "overall_on_time_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overall_attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.RenameField(
            model_name="dailyreport",
            old_name="delayed_trips",
            new_name="cancelled_trips",
        ),
        migrations.RenameField(
            model_name="dailyreport",
            old_name="on_time_trips",
            new_name="critical_issues",
        ),
        migrations.RenameField(
            model_name="dailyreport",
            old_name="total_students",
            new_name="in_progress_trips",
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="average_delay_minutes",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="late_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="on_time_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="total_distance_km",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="total_duration_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="total_issues",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="total_late",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="total_students_transported",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tripperformance",
            name="average_speed",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="tripperformance",
            name="driver_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="tripperformance",
            name="issues_reported",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tripperformance",
            name="parent_feedback_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tripperformance",
            name="stops_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tripperformance",
            name="stops_total",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="RoutePerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_trips", models.IntegerField(default=0)),
                ("completed_trips", models.IntegerField(default=0)),
                ("average_duration", models.IntegerField(default=0)),
                (
                    "on_time_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_delay_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_students_per_trip",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.route"
                    ),
                ),
            ],
            options={
                "db_table": "route_performance_reports",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DriverPerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_trips", models.IntegerField(default=0)),
                ("completed_trips", models.IntegerField(default=0)),
                ("cancelled_trips", models.IntegerField(default=0)),
                ("on_time_trips", models.IntegerField(default=0)),
                ("delayed_trips", models.IntegerField(default=0)),
                (
                    "on_time_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_delay_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("total_ratings", models.IntegerField(default=0)),
                ("total_issues", models.IntegerField(default=0)),
                ("critical_issues", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_performance_reports",
                "ordering": ["-start_date"],
            },
        ),
    ]
