# Generated by Django 4.2.7 on 2025-11-19 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Tài xế", "verbose_name_plural": "Tài xế"},
        ),
        migrations.AlterModelOptions(
            name="parent",
            options={"verbose_name": "Phụ huynh", "verbose_name_plural": "Phụ huynh"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Người dùng",
            },
        ),
        migrations.AlterField(
            model_name="driver",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="experience_years",
            field=models.IntegerField(default=0, verbose_name="Số năm kinh nghiệm"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_expiry",
            field=models.DateField(verbose_name="Ngày hết hạn GPLX"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Số giấy phép lái xe"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="rating",
            field=models.DecimalField(
                decimal_places=2, default=5.0, max_digits=3, verbose_name="Đánh giá"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Sẵn sàng"),
                    ("on_trip", "Đang chạy"),
                    ("off_duty", "Nghỉ việc"),
                ],
                default="available",
                max_length=20,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="routes.vehicle",
                verbose_name="Xe được gán",
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="address",
            field=models.TextField(verbose_name="Địa chỉ"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="emergency_contact",
            field=models.CharField(max_length=20, verbose_name="Liên hệ khẩn cấp"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người dùng",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Ảnh đại diện"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=255, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="FCM Token"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Họ và tên"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Là nhân viên"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Đã xác thực"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Đăng nhập lần cuối"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Mật khẩu"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 chữ số.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Số điện thoại",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Quản trị viên"),
                    ("driver", "Tài xế"),
                    ("parent", "Phụ huynh"),
                ],
                max_length=20,
                verbose_name="Vai trò",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_index=True, max_length=150, unique=True, verbose_name="Tên đăng nhập"
            ),
        ),
    ]
